'Day 2: 30 Days of python programming'
first_name = 'Zainab'
last_name = 'Ibrahim'
full_name = 'Zainab yau'
country = 'Nigeria'
city = 'Zaria'
age = '100'
year = '2023'
is_married = 'True'
is_true = 'True'
is_light_on = 'False'
first_name last_name country, age, is_married = 'Zainab', ' Ibrahim', 'Nigeria', '100', 'True'